### ISSUE TITLE
Delete is rebinded in every buffer to `emacs-everywhere-erase-buffer`

### ISSUE THREAD

**Issue by ipvych** [tecosaur/emacs-everywhere#49] opened 2022-05-05 14:45 UTC
When emacs-everywhere is called from terminal using `emacsclient --eval '(emacs-everywhere)'` in every buffer delete gets rebinded to `emacs-everywhere-erase-buffer-command` and it stays so until `emacs-everywhere-mode` is enabled and disabled manually, then pressing delete key will erase buffer once and after undoing that erase key will return to normal behavior.

Steps to reproduce:
1. `emacs -Q --daemon`
2. `emacsclient`
3. Install emacseverywhere
4. `emacsclient --eval '(emacs-everywhere)'`
5. Finish using either `C-c C-c` or `C-x 5 0`
6. Press delete in any Emacs buffer

Output of `emacs-version`: `GNU Emacs 28.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0)`
Display server: x11
Distribution: NixOS 22.05 (Quokka)

**Comment by ivan-pop** [comment] 2022-05-05 15:09
Evaluating `(setq emacs-everywhere-mode-initial-map nil)` as per docstring of that variable to make it so that this map never activates seems to solve issue. For me this is enough to fix since I don't use that feature anyway, but keeping ths issue open in case there is some fix to this without disabling map.

**Comment by hp27596** [comment] 2022-07-08 18:37
I'm having this problem too except `emacs-everywhere-erase-buffer` is binded to backspace instead of del, and it won't go away.

If I eval the expression `(setq emacs-everywhere-mode-initial-map nil)`, my keyboard is locked when I finish `emacs-everywhere` and I'm unable to press any key until what I found out is to press Ctrl-c anywhere in the desktop. 

I'm using Doom Emacs with it.

**Comment by ronisbr** [comment] 2023-01-17 13:47
Hi @hyrodium !

In a typical scenario, I would say why not! However, ReferenceFrameRotations.jl is used here at INPE for satellite simulators and analyses.

Since we do not have time right now to update all the tools we have, the migration must respect some points:

1. Everything must be the same, with no API or breaking changes. This includes, for example, the naming convention for the quaternion elements and the output print to `stdout`.
2. The speed of each operation must be equal or better. We have spent tons of hours optimizing everything, and every ms counts when you run a code 1,000,000,000x :)
3. This is probably the hardest one: the operations must use the same equations in the same order. All the code is tested by comparing the result to machine epsilon to ensure nothing changes. Hence, I am pretty sure that if we use different ordering when computing, for example, the quaternion multiplication, it will lead to different results when analyzing the least significant bits.
4. This is a horrible request, but I will also need it since this package is used for daily tasks related to the space program: I will need to have write access to the repository. Sometimes you need to do something different and spot a bug. Since all operations must be reproducible, I store the envs for all the things to allow for review. Hence, sometimes I must make a quick and **very** fast change to the repository code.

If you are willing to adapt Quaternions.jl to attend those points, we can try to integrate it with ReferenceFrameRotations.jl :) However, I fully understand if you decide not to since those are not common asks in open-source development.

I am really sorry for those demands, but this package is really crucial for daily work here.

**Comment by tecosaur** [comment] 2023-01-17 13:59
For what it's worth, I have seen this issue but have not been able to reproduce it. The key map should only be applying locally.

**Comment by ronisbr** [comment] 2023-01-17 14:03
I can confirm that I am also not seeing this issue in Doom Emacs + Emacs 29.

**Comment by doyougnu** [comment] 2023-04-21 11:43
I'm on emacs-28.3 and Doom. This worked for me: `(setq emacs-everywhere-mode-initial-map nil)`

**Comment by ipvych** [comment] 2023-06-04 23:08
I am no longer having this issue in emacs master and 28.2.

**Comment by tecosaur** [comment] 2024-04-11 04:29
I'll close this issue for now, don't hesitate to ask me to reopen if you run into this again!

**Closed by tecosaur** 2024-04-11 04:29 UTC
Labels: bug
